--server:
  port: 8181
info:
  app:
    description: This sample application allows to create event in calendar
    name: Event calendar application
    version: 1.0.0
compression:
  enabled: true
  mimi_types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.description.sql.BasicBinder: TRACE
    blog: WARN
    org: WARN
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, httptrace, metrics, threaddump, heapdump, shutdown,
          beans
  trace:
    http:
      enabled: true
spring:
  datasource:
#    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/event_calendar?createDatabaseIfNotExist=true&amp"
#    username: "${DB_USER:root}"
#    password: "#{DB_PASSWORD:A4620692!}"
    url: jdbc:mysql://localhost:3306/event_calendar?createDatabaseIfNotExist=true&amp
    username: "root"
    password: "A4620692!"
    continueOnError: true
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      show_sql: true
      use_sql_comments: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            client-id:
#            client-secret:
#
  thymeleaf:
    cache: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  resources:
    cache:
      cachecontrol:
        max-age: 30d
    chain:
      strategy:
        content:
          enabled: true
          path: /css/**
